# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none
parameters:
  - name: region
    type: string
    default: "USR2"
    displayName: Select Region
    values: 
      - USR1
      - USR2
      - UKR1
      - UKR2
      - AUA1
      - AUA2
      - DEA1
      - DEA2

  - name: environment
    type: string
    default: "dev"
    displayName: Select environment
    values: 
      - prod
      - test
      - dev


pool:
  name: linux-agent
  vmImage: linux-agent

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: $(gradle-build)
    tasks: $(build-task)
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
